server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #绑定rabbitmq服务信息
        defaultRabbit: #定义名称
          type: rabbit #消息组件类型
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #服务整合处理
        input: #通道名称
          destination: studyExchange  #使用的Exchange名称
          content-type: application/json  #设置消息类型
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: atguiguA

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7701/eureka

  instance:
    lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔
    lease-expiration-duration-in-seconds: 5 #如果现在超过5秒的间隔
    instance-id: receive-8802.com #信息列表显示的主机名称
    prefer-ip-address: true #访问的路径变为ip地址