server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置nacos地址
        server-addr: 192.168.83.145:1111 

management:
  endpoints:
    web:
      exposure:
        include: '*'