server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由id，唯一
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          #filters:
            #- AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/get/**  #断言，路径匹配的路由地址
            - After=2022-05-21T19:11:15.091+08:00[Asia/Shanghai]
            #- Before=2022-05-21T19:01:15.091+08:00[Asia/Shanghai]
            #- Between=2022-05-21T19:11:15.091+08:00[Asia/Shanghai],2022-05-21T19:01:15.091+08:00[Asia/Shanghai]
            #- Cookie=username,gaohao
            #- Header=X-Request-Id, \d+  #请求头要有X-Request属性并且值为整数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username,\d+  #要有参数名为username并且值为整数

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
