server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1  #采样率介于0到1，1表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/alienware?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    #true表示将自己注册到注册中心
    register-with-eureka: true
    #true表示从EurekaServer抓取已有的注册信息，要想配合ribbon使用负载均衡必须为true
    fetch-registry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://localhost:7001/eureka,http://alienware:7002/eureka/
  instance:
    instance-id: payment8001
    #访问路径显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-renewal-interval-in-seconds: 1
    #Eureka客户端在收到最后一次心跳后等待时间上限，超时将剔除服务，单位为秒
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
