#person:
#  userName: zhangsan
#  boss: true
#  birth: 2022/5/9
#  age: 18
#  interests:
#    - 金球
#    - 银球
#  animal: [ 猫,狗 ]
#  score: { english:80,math:90 }
#  salarys:
#    - 99.99
#    - 99.99
#  pet:
#    name: 狗
#    weight: 99.99
#  allPets:
#    sick:
#      - name: 狗
#        weight: 99.99
#      - name: 猫
#        weight: 99.99
#    health:
#      - name: 猪
#        weight: 99.99
#      - name: 驴
#        weight: 99.99

spring:
  mvc:
    static-path-pattern: /res/**
    hiddenmethod:
      filter:
        enabled: true
  resources:
    static-locations: [classpath:/img/]
    add-mappings: false